version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://192.227.148.23:8081
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysql7
      - DB_USER=root
      - DB_PASSWORD=fX5{vP2,eY4
      - DB_NAME=devSync

networks:
  default:
      external: true
      name: devops
